ALTER TABLE users ADD COLUMN total_opened INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN total_collected INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN avatar TEXT DEFAULT '🐱';
ALTER TABLE users ADD COLUMN frame TEXT DEFAULT 'default';