ALTER TABLE users ADD COLUMN daily_last_claim INTEGER DEFAULT NULL;
ALTER TABLE users ADD COLUMN daily_streak INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN daily_bag TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN daily_position INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN boost_type TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN boost_expires_at INTEGER DEFAULT 0;